# Generated by Django 5.2.7 on 2025-12-06 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=45)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('variacao', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoFavoritada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação Favoritada',
                'unique_together': {('usuario', 'acao')},
            },
        ),
    ]
