# Generated by Django 5.2.7 on 2025-11-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='variacao',
            field=models.FloatField(default=0.0),
        ),
    ]
